language: java
sudo: false # faster builds

jdk:
    - oraclejdk11
    - oraclejdk8
script:
    - travis_wait 30 mvn clean cobertura:cobertura package

after_success:
  - bash <(curl -s https://codecov.io/bash)
